# Site settings
title: YuronkDev
email: your-email@domain.com
url: 
description: "Hi, my name is Yuronk and I'm currently working on Tower of Altheon."
keywords: "hydrated, unbothered, moisturized"
skills: "Game Developer — Working on Tower of Altheon"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2d362d #altheon green
  primary-rgb: "45,54,45"
  secondary: d0a933 #altheon gold
  secondary-dark: 967922 #altheon gold, slightly darker

# Footer settings
footer:
  copyright: YuronkDev
  location: 
  social: Follow My Progress!
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://x.com/yuronkdev
  - title: bluesky
    url: https://bsky.app/profile/comradeyuronk.bsky.social
  - title: instagram
    url: https://www.instagram.com/yuronkdev/
  - title: reddit
    url: https://www.reddit.com/user/Theodore179/
  - title: youtube
    url: https://www.youtube.com/@yuronkdev/featured

# Postal address (add as many lines as necessary)
address:

# Credits content
credits:

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
